PAIRS = [
    ("SPY", "IVV"),
    ("GLD", "GDX"),
    ("XOM", "CVX"),
    ("DAL", "UAL"),
    ("QQQ", "XLK"),
]

SYMBOLS = list({sym for pair in PAIRS for sym in pair})

INTERVAL = "1d"
TRADE_OUTSIDE_HOURS = False

FORMATION_DAYS = 252

COINT_PVALUE_THRESHOLD = 0.05
HLIFE_MIN_DAYS = 2.0
HLIFE_MAX_DAYS = 30.0

KALMAN_DELTA = 1e-4
KALMAN_OBS_NOISE = 1e-3

ENTRY_ZSCORE = 2.0
EXIT_ZSCORE = 0.5
STOPLOSS_ZSCORE = 3.5
MAX_HOLDING_DAYS = 90
REENTRY_COOLDOWN_DAYS = 10

POSITION_SIZE_USD = 10_000

VIX_BLACKOUT_DAILY_MOVE = 0.10
