SYMBOLS = ["AAPL", "MSFT", "GOOGL", "AMZN", "META", "NVDA", "TSLA", "JPM", "JNJ", "UNH"]
MARKET_PROXY = "SPY"

INTERVAL = "1d"
TRADE_OUTSIDE_HOURS = False

FORMATION_DAYS = 252
ROLLING_WINDOW = 60

ENTRY_ZSCORE = 2.0
EXIT_ZSCORE = 0.5
STOPLOSS_ZSCORE = 3.5
MAX_HOLDING_DAYS = 60
REENTRY_COOLDOWN_DAYS = 10

POSITION_SIZE_USD = 10_000
