SYMBOLS = [
    "AAPL", "MSFT", "GOOGL", "AMZN", "META", "NVDA", "TSLA", "JPM", "JNJ", "UNH",
    "V", "PG", "HD", "MA", "ABBV", "PFE", "KO", "PEP", "TMO", "COST",
    "AVGO", "CSCO", "ACN", "LLY", "DHR", "VZ", "ADBE", "CRM", "NEE", "RTX",
]

MOM_LOOKBACK = 252
REV_LOOKBACK = 21
VOL_LOOKBACK = 63
REBALANCE_FREQ = 21
TOP_PCT = 0.20
POSITION_SIZE_USD = 10_000
INTERVAL = "1d"
TRADE_OUTSIDE_HOURS = False
